name: symbolism
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.14=hb9d3cd8_0
  - aom=3.9.1=hac33072_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attr=2.5.1=h166bdaf_1
  - brotli-python=1.1.0=py312h2ec8cdc_2
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.7.14=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - certifi=2025.7.14=pyhd8ed1ab_0
  - cffi=1.17.1=py312h06ac9bb_0
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - dav1d=1.2.1=hd590300_0
  - dbus=1.16.2=h3c4dab8_0
  - debugpy=1.8.14=py312h2ec8cdc_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - ffmpeg=7.1.1=gpl_h127656b_906
  - filelock=3.18.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-noto-cjk=2.004=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.13.3=ha770c72_1
  - fribidi=1.0.10=h36c2ea0_0
  - fsspec=2025.5.0=pyhd8ed1ab_0
  - gdk-pixbuf=2.42.12=hb9ae30d_0
  - gettext=0.24.1=h5888daf_0
  - gettext-tools=0.24.1=h5888daf_0
  - gmp=6.3.0=hac33072_2
  - google-cloud-sdk=529.0.0=py312h7900ff3_0
  - graphite2=1.3.14=h5888daf_0
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=11.2.1=h3beb420_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - huggingface_hub=0.31.4=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - ipykernel=6.29.5=pyh3099207_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - ld_impl_linux-64=2.43=h712a8e2_4
  - lerc=4.0.0=h0aef613_1
  - level-zero=1.22.5=h84d6215_0
  - libabseil=20250127.1=cxx17_hbbce691_0
  - libasprintf=0.24.1=h8e693c7_0
  - libasprintf-devel=0.24.1=h8e693c7_0
  - libass=0.17.3=h52826cd_2
  - libcap=2.75=h39aace5_0
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.125=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libflac=1.4.3=h59595ed_0
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgettextpo=0.24.1=h5888daf_0
  - libgettextpo-devel=0.24.1=h5888daf_0
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.2=h3618099_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.1.0=h767d61c_2
  - libgpg-error=1.55=h3f2d84a_0
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblzma=5.8.1=hb9d3cd8_1
  - libnsl=2.0.1=hd590300_0
  - libogg=1.3.5=hd0c01bc_1
  - libopenvino=2025.0.0=hdc3f47d_3
  - libopenvino-auto-batch-plugin=2025.0.0=h4d9b6c2_3
  - libopenvino-auto-plugin=2025.0.0=h4d9b6c2_3
  - libopenvino-hetero-plugin=2025.0.0=h981d57b_3
  - libopenvino-intel-cpu-plugin=2025.0.0=hdc3f47d_3
  - libopenvino-intel-gpu-plugin=2025.0.0=hdc3f47d_3
  - libopenvino-intel-npu-plugin=2025.0.0=hdc3f47d_3
  - libopenvino-ir-frontend=2025.0.0=h981d57b_3
  - libopenvino-onnx-frontend=2025.0.0=h0e684df_3
  - libopenvino-paddle-frontend=2025.0.0=h0e684df_3
  - libopenvino-pytorch-frontend=2025.0.0=h5888daf_3
  - libopenvino-tensorflow-frontend=2025.0.0=h684f15b_3
  - libopenvino-tensorflow-lite-frontend=2025.0.0=h5888daf_3
  - libopus=1.5.2=hd0c01bc_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.49=h943b412_0
  - libprotobuf=5.29.3=h501fc15_1
  - librsvg=2.58.4=he92a37e_3
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.49.2=hee588c1_0
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-ng=15.1.0=h4852527_2
  - libsystemd0=257.6=h4e0b6ca_0
  - libtiff=4.7.0=hf01ce69_5
  - libudev1=257.6=hbe16f8c_0
  - libunwind=1.6.2=h9c3ff4c_0
  - liburing=2.10=h84d6215_0
  - libusb=1.0.29=h73b1eb8_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.22.0=h4f16b4b_2
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.14.1=hac33072_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.10.0=h65c71a3_0
  - libxml2=2.13.8=h4bc477f_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mecab=0.996=h4bd325d_0
  - mecab-python3=1.0.8=py312h30efb56_0
  - mpg123=1.32.9=hc50e24c_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openh264=2.6.0=hc22cd8d_0
  - openssl=3.5.1=h7b32b05_0
  - packaging=25.0=pyh29332c3_1
  - pango=1.56.3=h9ac818e_1
  - parso=0.8.4=pyhd8ed1ab_1
  - pcre2=10.45=hc749103_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.1.1=pyh8b19718_0
  - pixman=0.46.2=h29eaf8c_0
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py312h66e93f0_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pugixml=1.15=h3f63f65_0
  - pulseaudio-client=17.0=hac146a9_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.10=h9e4cc4f_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.12=7_cp312
  - pyyaml=6.0.2=py312h178313f_2
  - readline=8.2=h8c095d6_2
  - requests=2.32.3=pyhd8ed1ab_1
  - sdl2=2.32.54=h3f2d84a_0
  - sdl3=3.2.16=he3e324a_0
  - six=1.17.0=pyhd8ed1ab_0
  - snappy=1.2.1=h8bd8927_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - svt-av1=3.0.2=h5888daf_0
  - tbb=2022.1.0=h4ce085d_0
  - tk=8.6.13=noxft_h4845f30_101
  - tokenizers=0.21.1=py312h8360d73_0
  - tornado=6.5.1=py312h66e93f0_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.13.2=h0e9735f_0
  - typing_extensions=4.13.2=pyh29332c3_0
  - urllib3=2.4.0=pyhd8ed1ab_0
  - wayland=1.23.1=h3e06ad9_1
  - wayland-protocols=1.45=hd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xkeyboard-config=2.45=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxscrnsaver=1.2.4=hb9d3cd8_0
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.5=h3b0a872_7
  - zstandard=0.23.0=py312h66e93f0_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - accelerate==1.7.0
      - adjusttext==1.3.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - airportsdata==20250224
      - annotated-types==0.7.0
      - anyio==4.9.0
      - astor==0.8.1
      - attrs==25.3.0
      - audioread==3.0.1
      - av==14.4.0
      - blake3==1.0.5
      - cachetools==5.5.2
      - click==8.1.8
      - cloudpickle==3.1.1
      - compressed-tensors==0.9.3
      - contourpy==1.3.2
      - cupy-cuda12x==13.4.1
      - cycler==0.12.1
      - decord==0.6.0
      - deprecated==1.2.18
      - depyf==0.18.0
      - dill==0.4.0
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.7.0
      - editdistance==0.8.1
      - einops==0.8.1
      - email-validator==2.2.0
      - espeakng-loader==0.2.4
      - fastapi==0.115.12
      - fastapi-cli==0.0.7
      - fastrlock==0.8.3
      - ffmpeg-python==0.2.0
      - flash-attn==2.7.4.post1
      - fonttools==4.58.0
      - frozenlist==1.6.0
      - future==1.0.0
      - genai==2.1.0
      - gguf==0.16.3
      - google-auth==2.40.3
      - google-genai==1.23.0
      - googleapis-common-protos==1.70.0
      - grpcio==1.71.0
      - gtts==2.5.4
      - h11==0.16.0
      - h5py==3.14.0
      - hf-xet==1.1.2
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - importlib-metadata==8.0.0
      - interegular==0.3.3
      - ipython==8.37.0
      - jinja2==3.1.6
      - jiter==0.10.0
      - joblib==1.5.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.4.1
      - kiwisolver==1.4.8
      - lark==1.2.2
      - lazy-loader==0.4
      - librosa==0.11.0
      - llguidance==0.7.24
      - llvmlite==0.44.0
      - lm-format-enforcer==0.10.11
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - mdurl==0.1.2
      - mistral-common==1.5.5
      - mpmath==1.3.0
      - msgpack==1.1.0
      - msgspec==0.19.0
      - multidict==6.4.4
      - munkres==1.1.4
      - networkx==3.4.2
      - ninja==1.11.1.4
      - numba==0.61.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - openai==1.93.0
      - opencv-python-headless==4.11.0.86
      - opentelemetry-api==1.26.0
      - opentelemetry-exporter-otlp==1.26.0
      - opentelemetry-exporter-otlp-proto-common==1.26.0
      - opentelemetry-exporter-otlp-proto-grpc==1.26.0
      - opentelemetry-exporter-otlp-proto-http==1.26.0
      - opentelemetry-proto==1.26.0
      - opentelemetry-sdk==1.26.0
      - opentelemetry-semantic-conventions==0.47b0
      - opentelemetry-semantic-conventions-ai==0.4.9
      - outlines==0.1.11
      - outlines-core==0.1.26
      - pandas==2.3.0
      - panphon==0.22.2
      - partial-json-parser==0.2.1.1.post5
      - pillow==11.2.1
      - pooch==1.8.2
      - prometheus-client==0.22.0
      - prometheus-fastapi-instrumentator==7.1.0
      - propcache==0.3.1
      - protobuf==4.25.7
      - py-cpuinfo==9.0.0
      - py-espeak-ng==0.1.8
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycountry==24.6.1
      - pydantic==2.11.5
      - pydantic-core==2.33.2
      - pydub==0.25.1
      - pygments==2.19.1
      - pyparsing==3.2.3
      - python-dotenv==1.1.0
      - python-json-logger==3.3.0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyzmq==26.4.0
      - qwen-omni-utils==0.0.4
      - ray==2.46.0
      - referencing==0.36.2
      - regex==2024.11.6
      - rich==14.0.0
      - rich-toolkit==0.14.6
      - rpds-py==0.25.1
      - rsa==4.9.1
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - setuptools==80.9.0
      - setuptools-rust==1.11.1
      - shellingham==1.5.4
      - simpledorff==0.0.2
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soxr==0.5.0.post1
      - starlette==0.46.2
      - sympy==1.13.1
      - tabulate==0.9.0
      - tenacity==8.5.0
      - threadpoolctl==3.6.0
      - tiktoken==0.3.3
      - torch==2.6.0
      - torchaudio==2.6.0
      - torchlibrosa==0.1.0
      - torchvision==0.21.0
      - transformers==4.52.3
      - triton==3.2.0
      - typer==0.15.4
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - unicodecsv==0.14.1
      - uvicorn==0.34.2
      - uvloop==0.21.0
      - vllm==0.8.4
      - watchfiles==1.0.5
      - websockets==15.0.1
      - wrapt==1.17.2
      - xformers==0.0.29.post2
      - xgrammar==0.1.18
      - yarl==1.20.0
      - zipp==3.21.0
